### ISSUE TITLE
Readme is confusing

### ISSUE THREAD

**Issue by munawariz** [GaniyaMustafa/PIRUS#1]
The readme doesn't really explained anything, or im just stupid? idk

**Comment by GaniyaMustafa** [comment]
you are stupid idk

**Comment by ganiyamustafa** [comment]
> The readme doesn't really explained anything, or im just stupid? idk

you are stupid idk

**Comment by munawariz** [comment]
Ini aku benerin #2

**Comment by munawariz** [comment]
udah bener aku close ya
